find_path(Readline_INCLUDE_DIR readline/readline.h)
find_library(Readline_LIBRARY NAMES readline) 

if (Readline_INCLUDE_DIR AND Readline_LIBRARY)
  set (Readline_FOUND TRUE)
endif ()

if (Readline_FOUND)
  if (NOT Readline_FIND_QUIETLY)
    message(STATUS "Found GNU Readline: ${Readline_LIBRARY}")
  endif ()
else ()
  if (Readline_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find GNU Readline")
  endif ()
endif ()